# Generated by Django 5.0.1 on 2024-02-11 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('height', models.IntegerField()),
            ],
            options={
                'db_table': 'pass_coordinates',
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winter_level', models.CharField(blank=True, max_length=5)),
                ('summer_level', models.CharField(blank=True, max_length=5)),
                ('autumn_level', models.CharField(blank=True, max_length=5)),
                ('spring_level', models.CharField(blank=True, max_length=5)),
            ],
            options={
                'db_table': 'pass_level',
                'ordering': [-1],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('second_name', models.CharField(max_length=25)),
                ('otc', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'db_table': 'pass_user',
            },
        ),
        migrations.CreateModel(
            name='Pass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('beauty_title', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('other_titles', models.CharField(max_length=255)),
                ('connect', models.CharField(blank=True, max_length=255)),
                ('add_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('new', 'new data'), ('pending', 'The data is being processed'), ('accepted', 'Processing is successful'), ('rejected', 'The data is not accepted')], default='new', max_length=10)),
                ('coordinates', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.coordinates')),
                ('level', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='API.level')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.user')),
            ],
            options={
                'db_table': 'pass_pass',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=35)),
                ('data', models.BinaryField()),
                ('passes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='API.pass')),
            ],
            options={
                'db_table': 'pass_images',
            },
        ),
    ]
